/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-09 04:31:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addMember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1605611870166L));
    _jspx_dependants.put("jar:file:/D:/Spring%20WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("\t<title>멤버 추가 하기</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<select id=\"GroupList\"></select>\r\n");
      out.write("\t<script id=\"tempList\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t{{#each .}}\r\n");
      out.write("\t\t<option value=\"{{g_code}}\">{{g_name}}</option>\r\n");
      out.write("        {{/each}}\r\n");
      out.write("\t</script>   \r\n");
      out.write("\r\n");
      out.write("\t<input type=\"text\" id=\"query\" placeholder=\"아이디를 검색하시오\">\r\n");
      out.write("\t<button id=\"search\">검색</button>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t<h1>검색 결과</h1>\r\n");
      out.write("\t<div id=\"result\"></div>\r\n");
      out.write("\t<script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t{{#each .}}\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<input type=\"checkbox\" value=\"{{id}}\" name=\"selectedMember\">\t\t\t\r\n");
      out.write("\t\t\t이름 : {{name}} \r\n");
      out.write("\t\t\t아이디 : {{id}} \r\n");
      out.write("      \t</div>\t\r\n");
      out.write("\t\t{{/each}}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<input type=\"button\" id=\"complete\" value=\"완료\">\r\n");
      out.write("\t<button onClick=\"location.href='/'\">돌아가기</button>\r\n");
      out.write("</body>\r\n");
      out.write("<script >\r\n");
      out.write("\tGroupList();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction GroupList(){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype :\"get\",\r\n");
      out.write("\t\t\turl : \"myGroup\",\r\n");
      out.write("\t\t    dataType : \"json\",\r\n");
      out.write("\t\t    success : function(data){\r\n");
      out.write("\t\t    \tvar temp = Handlebars.compile($(\"#tempList\").html());\r\n");
      out.write("\t\t\t\t$(\"#GroupList\").html(temp(data));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$(\"#search\").on(\"click\",function(){\r\n");
      out.write("\t\tvar query = $(\"#query\").val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype :\"get\",\r\n");
      out.write("\t\t    url : \"searchGroupMember\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t    data : {\"query\" : query},\r\n");
      out.write("\t\t    success : function(data){\r\n");
      out.write("\t\t    \tvar temp = Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("\t            $(\"#result\").html(temp(data));\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#complete\").on(\"click\",function(){\r\n");
      out.write("      var g_code = $(\"#GroupList\").val(); // session에서 g_code를 가져온다. → 맴버를 초대할 모임을 선택하도록 했다.\r\n");
      out.write("      var gu_pwchk= \"N\";\r\n");
      out.write("      var check_count = document.getElementsByName(\"selectedMember\").length;\r\n");
      out.write("      for(var i=0; i<check_count; i++){\r\n");
      out.write("         if (document.getElementsByName(\"selectedMember\")[i].checked == true) {\r\n");
      out.write("            // 친구 초대하는 ajax 실행하면 됨\r\n");
      out.write("            var id=document.getElementsByName(\"selectedMember\")[i].value;\r\n");
      out.write("            \r\n");
      out.write("            $.ajax({\r\n");
      out.write("               type :\"get\",\r\n");
      out.write("                url : \"addMembers\",\r\n");
      out.write("                data : {\"g_code\" : g_code, \"gu_pwchk\" :gu_pwchk,\"id\":id},\r\n");
      out.write("                success : function(){\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("         }\r\n");
      out.write("      }\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
