/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-16 12:14:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cn_005freply_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1605611870166L));
    _jspx_dependants.put("jar:file:/D:/Spring%20WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/Spring%20WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FP/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/mainClup.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"right_page2-re\">\r\n");
      out.write("\t\t<p class=\"mainTitle\">댓글목록</p>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"divReply\"></div>\r\n");
      out.write("\t\t<script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t{{#each list}}\r\n");
      out.write("\t\t\t<ul class=\"right_page2-re-re\">\r\n");
      out.write("\t\t\t\t<li>{{id}}</li>\r\n");
      out.write("\t\t\t\t<li>{{cnr_content}}</li>\r\n");
      out.write("\t\t\t\t<li>{{cnr_regdate}}<input type=\"button\" cnr_no=\"{{cnr_no}}\" rn=\"{{rn}}\" wid={{id}} value=\"삭제\" class=\"btnreDel\"></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t{{/each}}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t<div class=\"page_wrap3\">\r\n");
      out.write("\t\t\t<div id=\"pagination\" class=\"pagination\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"insertReply\" class=\"right_page2-re-wh\">\r\n");
      out.write("\t\t\t<p class=\"mainTitle\">댓글등록</p>\r\n");
      out.write("\t\t\t<textarea class=\"list_content3\" placeholder=\"내용을 입력하세요\" id=\"txtReply\"></textarea>\r\n");
      out.write("\t\t\t<input type=\"button\" value=\"등록\" class=\"whbutton\" id=\"btnReply\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar page = 1;\r\n");
      out.write("\tgetList();\r\n");
      out.write("\r\n");
      out.write("\t$(\"#divReply\").on(\"click\", \"button\", function() {\r\n");
      out.write("\t\tvar cnr_no = $(this).attr(\"cnr_no\");\r\n");
      out.write("\t\tvar rn = $(this).attr(\"rn\");\r\n");
      out.write("\t\tif (!confirm(rn + \"번 댓글을 삭제하실래요?\"))\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\turl : \"cnrDelete\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\"cnr_no\" : cnr_no\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function() {\r\n");
      out.write("\t\t\t\tgetList();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#txtReply\").keydown(function(key) {\r\n");
      out.write("\t\tif (key.keyCode == 13) {\r\n");
      out.write("\t\t\t$(\"#btnReply\").click();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#btnReply\").on(\"click\", function() {\r\n");
      out.write("\t\tvar reply = $(\"#txtReply\").val();\r\n");
      out.write("\t\tif (reply == \"\") {\r\n");
      out.write("\t\t\talert(\"내용을 입력해주세요\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (!confirm(\"등록하시겠습니까?\")) return;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\turl : \"insertCnReply\",\r\n");
      out.write("\t\t\tdata : { \"reply\" : reply },\r\n");
      out.write("\t\t\tsuccess : function() {\r\n");
      out.write("\t\t\t\t$(\"#txtReply\").val(\"\");\r\n");
      out.write("\t\t\t\tgetList();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\t$(\"#pagination\").on(\"click\", \"a\", function(e) {\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\tpage = $(this).attr(\"href\");\r\n");
      out.write("\t\tgetList();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction getList() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\turl : \"getCnReply\",\r\n");
      out.write("\t\t\tdata : { \"page\" : page },\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tvar temp = Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("\t\t\t\t$(\"#divReply\").html(temp(data));\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar str = \"\";\r\n");
      out.write("\t\t\t\tif (data.pm.prev) {\r\n");
      out.write("\t\t\t\t\tstr += \"<a href='\" + (data.pm.startPage - 1) + \"'>◀</a>\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tfor (var i = data.pm.startPage; i <= data.pm.endPage; i++) {\r\n");
      out.write("\t\t\t\t\tif (page == i) {\r\n");
      out.write("\t\t\t\t\t\tstr += \"[<a href='\"+ i +\"' class='active'>\" + i\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"</a>]\";\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tstr += \"[<a href='\"+ i +\"'>\" + i + \"</a>]\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif (data.pm.next) {\r\n");
      out.write("\t\t\t\t\tstr += \"<a href='\" + (data.pm.endPage + 1) + \"'>▶</a>\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#pagination\").html(str);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
