/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-02 06:46:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cnUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1605611870166L));
    _jspx_dependants.put("jar:file:/D:/Spring%20WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>동아리공지 수정</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h1>[동아리공지수정]</h1>\r\n");
      out.write("\t<form action=\"cnUpdatePost\" method=\"post\" name=\"frm\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"cn_no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnvo.cn_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t   \t<table border=1>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t    \t\t<td width=100>Title</td>\r\n");
      out.write("\t        \t<td width=500>\r\n");
      out.write("\t        \t\t<input type=\"text\" name=\"cn_title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnvo.cn_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp\r\n");
      out.write("\t        \t\t<input type=\"checkbox\" id=\"cn_bold\" name=\"cn_bold\" ");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("> 중요표시  \r\n");
      out.write("            \t\t<input type=\"checkbox\" id=\"cn_rchk\" name=\"cn_rchk\" ");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("> 댓글표시 \r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t        </tr>\r\n");
      out.write("\t        <tr>\r\n");
      out.write("\t        \t<td width=100>Writer</td>\r\n");
      out.write("\t            <td width=500><input type=\"text\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnvo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("\t        </tr>\r\n");
      out.write("\t        <tr>\r\n");
      out.write("\t            <td width=100>Content</td>\r\n");
      out.write("\t            <td width=500>\r\n");
      out.write("\t            \t<textarea rows=\"10\" cols=\"50\" name=\"cn_content\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnvo.cn_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("\t       \t\t</td>\r\n");
      out.write("\t        </tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<input type=\"submit\" value=\"수정\"> \r\n");
      out.write("\t\t<input type=\"reset\" value=\"취소\"> \r\n");
      out.write("\t\t<input type=\"button\" value=\"삭제\" id=\"btnDelete\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"목록\" onClick=\"location.href='club?c_code=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnvo.c_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "cn_reply.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("if ($(\"#cn_bold\").is(\":checked\")) {\r\n");
      out.write("    $(\"#cn_bold\").val(1);\r\n");
      out.write(" } else{\r\n");
      out.write("    $(\"#cn_bold\").val(0);\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" //중요표시벨류보내기\r\n");
      out.write(" $(\"#cn_bold\").on(\"change\", function(){\r\n");
      out.write("    if ($(\"#cn_bold\").is(\":checked\")) {\r\n");
      out.write("       $(\"#cn_bold\").val(1);\r\n");
      out.write("    } else{\r\n");
      out.write("       $(\"#cn_bold\").val(0);\r\n");
      out.write("    }\r\n");
      out.write(" });\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" if ($(\"#cn_rchk\").is(\":checked\")) {\r\n");
      out.write("    $(\"#cn_rchk\").val(1);\r\n");
      out.write(" } else{\r\n");
      out.write("    $(\"#cn_rchk\").val(0);\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" //댓글사용벨류보내기\r\n");
      out.write(" $(\"#cn_rchk\").on(\"change\", function(){\r\n");
      out.write("    if ($(\"#cn_rchk\").is(\":checked\")) {\r\n");
      out.write("       $(\"#cn_rchk\").val(1);\r\n");
      out.write("    } else {\r\n");
      out.write("       $(\"#cn_rchk\").val(0);\r\n");
      out.write("    }\r\n");
      out.write(" });\r\n");
      out.write("\r\n");
      out.write("\t//삭제버튼\r\n");
      out.write("\t$(\"#btnDelete\").on(\"click\",function(){\r\n");
      out.write("\t\tvar cn_no=$(frm.cn_no).val();\r\n");
      out.write("\t    if (!confirm(cn_no+\"를 삭제하시겟습니까?\"))return;\r\n");
      out.write("\t\tfrm.action=\"/cnDelete\";\r\n");
      out.write("\t\tfrm.method=\"post\";\r\n");
      out.write("\t\tfrm.submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t//서밋했을때\r\n");
      out.write("\t$(frm).submit(function(e) {\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\tvar cn_title=$(frm.cn_title).val();\r\n");
      out.write("\t\tvar cn_bold=$(frm.cn_bold).val();\r\n");
      out.write("\t\tvar cn_rchk=$(frm.cn_rchk).val();\r\n");
      out.write("\t\tvar cn_content=$(frm.cn_content).val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\talert(cn_title);\r\n");
      out.write("\t\tif ($(frm.cn_title).val() == \"\") {\r\n");
      out.write("\t\t\talert(\"글제목\");\r\n");
      out.write("\t\t\t$(frm.cn_title).focus();\r\n");
      out.write("\t\t} else if ($(frm.cn_content).val() == \"\") {\r\n");
      out.write("\t\t\talert(\"내용을 입력해주세요\");\r\n");
      out.write("\t\t\t$(frm.cn_content).focus();\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(cn_title+\"\\n\"+cn_bold+\"\\n\"+cn_rchk+\"\\n\"+cn_content);\r\n");
      out.write("\t\t\tif (!confirm(\"수정하시겠습니까?\"))return;\r\n");
      out.write("\t\t\tfrm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /WEB-INF/views/cnUpdate.jsp(21,62) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnvo.cn_bold == 1?'checked':'' }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent(null);
    // /WEB-INF/views/cnUpdate.jsp(22,65) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnvo.cn_rchk == 1?'checked':'' }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }
}
