/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-21 04:17:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class createMasterNotice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1605611870166L));
    _jspx_dependants.put("jar:file:/D:/Spring%20WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/Spring%20WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FP/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("<title>공지사항 글쓰기</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/clup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/notice.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("</div>\r\n");
      out.write("<p class=\"clupTitle\">공지사항 글쓰기</p>\r\n");
      out.write("\t<div id=\"div_contents\" class=\"contents2\">\r\n");
      out.write("\t<form action=\"createMasterNotice\" method=\"post\" name=\"frm\">\r\n");
      out.write("\t\t<div class=\"board_wrap01\">\r\n");
      out.write("\t\t\t<div class=\"board_ty_list\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"/\">홈으로</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"notice\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"event\">이벤트</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"QnA\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t\t<div class=\"textbox\">\r\n");
      out.write("\t\t\t   <div class=\"titler\" >\r\n");
      out.write("\t\t\t       <textarea name=\"n_title\" placeholder=\"제목을 입력해 주세요.\" class=\"title_input\" style=\"height: 40px;\"></textarea>\r\n");
      out.write("\t\t\t   </div>\r\n");
      out.write("\t\t\t   <div class=\"cont\">\r\n");
      out.write("\t\t       \t\t<textarea name=\"n_content\" placeholder=\"내용을 입력해 주세요\" class=\"cont_input\" style=\"height: 40px;overflow-y:visible\"></textarea>\r\n");
      out.write("\t\t\t   </div> \r\n");
      out.write("\t\t\t   <input type=\"button\" class=\"btnReturn\" value=\"목록\" onClick=\"location.href='event'\">\r\n");
      out.write("\t\t\t   <input type=\"submit\" class=\"btnSub\" value=\"저장\">\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("<div>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar start = true;\r\n");
      out.write("\t$(frm.n_content).on(\"click\", function() {\r\n");
      out.write("\t   if (start) {\r\n");
      out.write("\t      $(\"#n_content\").val(\"\");\r\n");
      out.write("\t   }\r\n");
      out.write("\t   start = false;\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t//서밋했을때\r\n");
      out.write("\t$(frm).submit(function(e) {\r\n");
      out.write("  \te.preventDefault();\r\n");
      out.write("  \tvar n_title=$(frm.n_title).val();\r\n");
      out.write("  \tvar n_content=$(frm.n_content).val();\r\n");
      out.write("  \r\n");
      out.write("  \tif ($(frm.n_title).val() == \"\") {\r\n");
      out.write("     \talert(\"제목을 입력해주세요\");\r\n");
      out.write("     \t$(frm.n_title).focus();\r\n");
      out.write("  \t}else if ($(frm.n_content).val() == \"\") {\r\n");
      out.write("     \talert(\"내용을 입력해주세요\");\r\n");
      out.write("     \t$(frm.n_content).focus();\r\n");
      out.write("  \t} else {\r\n");
      out.write("     \tif (!confirm(\"저장하시겠습니까?\")) return;\r\n");
      out.write("     \tfrm.submit();\r\n");
      out.write("  \t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
