/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-02 06:29:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class createNotice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>동아리공지글쓰기</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   \t<h1>동아리공지글쓰기</h1>\r\n");
      out.write("   \t<form name=\"frm\" action=\"createNotice\" method=\"post\">\r\n");
      out.write("      \t<table border=1>\r\n");
      out.write("         \t<tr>\r\n");
      out.write("            \t<td width=150>작성자</td>\r\n");
      out.write("            \t<td width=500>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("         \t</tr>\r\n");
      out.write("         \t<tr>\r\n");
      out.write("            \t<td width=150>글제목</td>\r\n");
      out.write("            \t<td width=500>\r\n");
      out.write("            \t\t<input type=\"text\" name = \"cn_title\" width=100 maxlength=\"25\">&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp\r\n");
      out.write("               \t\t<input type=\"checkbox\" name = \"cn_bold\" id=\"cn_bold\" value= \"0\"> 중요표시 \r\n");
      out.write("               \t\t<input type=\"checkbox\" name = \"cn_rchk\" id=\"cn_rchk\" value= \"0\"> 댓글표시</td>\r\n");
      out.write("         \t</tr>\r\n");
      out.write("         \t<tr>\r\n");
      out.write("            \t<td width=150>내용</td>\r\n");
      out.write("            \t<td width=500 style=\"text-align: center;\">\r\n");
      out.write("            \t\t<textarea rows=\"20\" cols=\"70\" name = \"cn_content\" id=\"cn_content\">글을 입력해주세요</textarea>\r\n");
      out.write("            \t</td>\r\n");
      out.write("         \t</tr>\r\n");
      out.write("\r\n");
      out.write("      \t</table>\r\n");
      out.write("      \t<input type=\"submit\" value=\"저장\"> \r\n");
      out.write("    \t<input type=\"reset\"  value=\"취소\">\r\n");
      out.write("\t</form>\r\n");
      out.write("   \t<button onClick=\"location.href='/'\">돌아가기</button>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("   \t$(\"#cn_bold\").change(function() {\r\n");
      out.write("      \tif ($(\"#cn_bold\").is(\":checked\")) {\r\n");
      out.write("         \t$(\"#cn_bold\").val(1);\r\n");
      out.write("      \t}else {\r\n");
      out.write("         \t$(\"#cn_bold\").val(0);\r\n");
      out.write("      \t}\r\n");
      out.write("   \t});\r\n");
      out.write("   \r\n");
      out.write("   \t$(\"#cn_rchk\").change(function() {\r\n");
      out.write("      \tif ($(\"#cn_rchk\").is(\":checked\")) {\r\n");
      out.write("         \t$(\"#cn_rchk\").val(1);\r\n");
      out.write("      \t}else {\r\n");
      out.write("         \t$(\"#cn_rchk\").val(0);\r\n");
      out.write("      \t}\r\n");
      out.write("   \t});\r\n");
      out.write("\r\n");
      out.write("   \tvar start = true;\r\n");
      out.write("   \t$(frm.cn_content).on(\"click\", function() {\r\n");
      out.write("      \tif (start) {\r\n");
      out.write("         \t$(\"#cn_content\").val(\"\");\r\n");
      out.write("      \t}\r\n");
      out.write("      \tstart = false;\r\n");
      out.write("   \t});\r\n");
      out.write("\r\n");
      out.write("  //서밋했을때\r\n");
      out.write("    $(frm).submit(function(e) {\r\n");
      out.write("       e.preventDefault();\r\n");
      out.write("       var cn_title=$(frm.cn_title).val();\r\n");
      out.write("       var cn_bold=$(frm.cn_bold).val();\r\n");
      out.write("       var cn_rchk=$(frm.cn_rchk).val();\r\n");
      out.write("       var cn_content=$(frm.cn_content).val();\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("       if ($(frm.cn_title).val() == \"\") {\r\n");
      out.write("          alert(\"글제목\");\r\n");
      out.write("          $(frm.cn_title).focus();\r\n");
      out.write("       } else if ($(frm.cn_content).val() == \"\") {\r\n");
      out.write("          alert(\"내용을 입력해주세요\");\r\n");
      out.write("          $(frm.cn_content).focus();\r\n");
      out.write("       } else {\r\n");
      out.write("          if (!confirm(\"입력하시겟습니까\"))\r\n");
      out.write("             return;\r\n");
      out.write("          frm.submit();\r\n");
      out.write("          alert(cn_title+\"\\n\"+cn_bold+\"\\n\"+cn_rchk+\"\\n\"+cn_content);\r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
