/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-11-26 05:22:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class createClub_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>동아리등록</title>\r\n");
      out.write("<style>\r\n");
      out.write("ul li.tag-item {\r\n");
      out.write("   padding: 4px 8px;\r\n");
      out.write("   background-color: #777;\r\n");
      out.write("   color: #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tag-item:hover {\r\n");
      out.write("   background-color: #262626;\r\n");
      out.write("   color: #fff;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <h1>동아리~~~~~~~~개설~~~</h1>\r\n");
      out.write("   <form action=\"insert\" method=\"post\" name=\"frm\">\r\n");
      out.write("      <table border=1>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td width=150>동아리이름</td>\r\n");
      out.write("            <td width=500><input type=\"text\" name=\"C_NAME\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td width=150>연락처공개여부</td>\r\n");
      out.write("            <td width=500>예 <input type=\"radio\" name=\"C_PCHK\" value=\"YInfo\"\r\n");
      out.write("               checked=\"checked\"> 아니오<input type=\"radio\" name=\"C_PCHK\"\r\n");
      out.write("               value=\"NInfo\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td width=150>카테고리</td>\r\n");
      out.write("            <td width=500><select name=\"C_CATEGORY\" value=\"관심사\">\r\n");
      out.write("                  <option value=\"게임\">게임</option>\r\n");
      out.write("                  <option value=\"운동\">운동</option>\r\n");
      out.write("                  <option value=\"낚시\">낚시</option>\r\n");
      out.write("                  <option value=\"자동차\">자동차</option>\r\n");
      out.write("            </select></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td width=150>태그</td>\r\n");
      out.write("            <td>\r\n");
      out.write("               <div class=\"content\">\r\n");
      out.write("                  <form action=\"insert\" method=\"POST\" id=\"tag-form\">\r\n");
      out.write("                     <input type=\"hidden\" value=\"\" name=\"tag\" id=\"rdTag\" />\r\n");
      out.write("                     <button onclick=\"btnHash\">태그등록</button>\r\n");
      out.write("                  </form>\r\n");
      out.write("                  <div>\r\n");
      out.write("                     <input type=\"text\" id=\"C_TAG\" size=\"7\" placeholder=\"태크엔터!\" />\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <ul id=\"tag-list\">\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td width=150>인삿말</td>\r\n");
      out.write("            <td width=500><input type=\"text\" name=\"C_WELCOME\"\r\n");
      out.write("               placeholder=\"환영의인사를해주세요\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td width=150>가입조건</td>\r\n");
      out.write("            <td width=500><textarea rows=\"10\" cols=\"50\" name=\"C_CONDITION\">\r\n");
      out.write("            </textarea></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td width=150>대표사진</td>\r\n");
      out.write("            <td width=500><img src=\"http://placehold.it/150x120\" id=\"image\"\r\n");
      out.write("               width=150> <input type=\"file\" name=\"C_PIC\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td width=150>활동장소</td>\r\n");
      out.write("            <td width=500><input type=\"text\" name=\"C_SPOT\"\r\n");
      out.write("               placeholder=\"어디서활동하세요?\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <input type=\"submit\" value=\"저장\"> <input type=\"reset\" value=\"취소\">\r\n");
      out.write("   </form>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("   //해쉬태그작동, 서버에 옮기기\r\n");
      out.write("   $(document)\r\n");
      out.write("         .ready(\r\n");
      out.write("               function() {\r\n");
      out.write("                  var C_TAG = {};\r\n");
      out.write("                  var counter = 0;\r\n");
      out.write("                  // 태그를 추가한다.\r\n");
      out.write("                  function addTag(value) {\r\n");
      out.write("                     C_TAG[counter] = value; // 태그를 Object 안에 추가\r\n");
      out.write("                     counter++; // counter 증가 삭제를 위한 del-btn 의 고유 id 가 된다.\r\n");
      out.write("                  }\r\n");
      out.write("                  // 최종적으로 서버에 넘길때 tag 안에 있는 값을 array type 으로 만들어서 넘긴다.\r\n");
      out.write("                  function marginTag() {\r\n");
      out.write("                     return Object.values(C_TAG).filter(function(word) {\r\n");
      out.write("                        return word !== \"\";\r\n");
      out.write("                     });\r\n");
      out.write("                  }\r\n");
      out.write("                  // 서버에 넘기기\r\n");
      out.write("                  function btnHash() {\r\n");
      out.write("                     var value = marginTag(); // return array\r\n");
      out.write("                     $(\"#rdTag\").val(value);\r\n");
      out.write("\r\n");
      out.write("                     $(this).submit();\r\n");
      out.write("                  }\r\n");
      out.write("\r\n");
      out.write("                  $(\"#C_TAG\")\r\n");
      out.write("                        .on( \"keypress\",\r\n");
      out.write("                              function(e) {\r\n");
      out.write("                                 var self = $(this);\r\n");
      out.write("                                 // input 에 focus 되있을 때 엔터 및 스페이스바 입력시 구동\r\n");
      out.write("                                 if (e.key === \"Enter\"\r\n");
      out.write("                                       || e.keyCode == 32) {\r\n");
      out.write("                                    var tagValue = self.val(); // 값 가져오기\r\n");
      out.write("                                    \r\n");
      out.write("                                    // 값이 없으면 동작 ㄴㄴ\r\n");
      out.write("                                    if (tagValue !== \"\") {\r\n");
      out.write("\r\n");
      out.write("                                       // 같은 태그가 있는지 검사한다. 있다면 해당값이 array 로 return 된다.\r\n");
      out.write("                                       var result = Object\r\n");
      out.write("                                             .values(C_TAG)\r\n");
      out.write("                                             .filter(\r\n");
      out.write("                                                   function(\r\n");
      out.write("                                                         word) {\r\n");
      out.write("                                                      return word === tagValue;\r\n");
      out.write("                                                   })\r\n");
      out.write("\r\n");
      out.write("                                       // 태그 중복 검사\r\n");
      out.write("                                       if (result.length == 0) {\r\n");
      out.write("                                          $(\"#tag-list\")\r\n");
      out.write("                                                .append(\r\n");
      out.write("                                                      \"<li class='tag-item'>\"\r\n");
      out.write("                                                            + tagValue\r\n");
      out.write("                                                            + \"<span class='del-btn' idx='\"+counter+\"'>x</span></li>\");\r\n");
      out.write("                                          addTag(tagValue);\r\n");
      out.write("                                          self.val(\"\");\r\n");
      out.write("                                       } else {\r\n");
      out.write("                                          alert(\"태그값이 중복됩니다.\");\r\n");
      out.write("                                       }\r\n");
      out.write("                                    }\r\n");
      out.write("                                    e.preventDefault(); // SpaceBar 시 빈공간이 생기지 않도록 방지\r\n");
      out.write("                                 }\r\n");
      out.write("                              });\r\n");
      out.write("\r\n");
      out.write("                  // 삭제 버튼은 비동기적 생성이므로 document 최초 생성시가 아닌 검색을 통해 이벤트를 구현시킨다.\r\n");
      out.write("                  $(document).on(\"click\", \".del-btn\", function(e) {\r\n");
      out.write("                     var index = $(this).attr(\"idx\");\r\n");
      out.write("                     C_TAG[index] = \"\";\r\n");
      out.write("                     $(this).parent().remove();\r\n");
      out.write("                  });\r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   //서밋했을때\r\n");
      out.write("   $(frm).submit(function(e) {\r\n");
      out.write("      e.preventDefault();\r\n");
      out.write("      var C_NAME = $(frm.C_NAME).val();\r\n");
      out.write("      var C_PCHK = $(frm.C_PCHK).val();\r\n");
      out.write("      var C_WELCOME = $(frm.C_WELCOME).val();\r\n");
      out.write("      var C_CONDITION = $(frm.C_CONDITION).val();\r\n");
      out.write("      var C_CATEGORY = $(frm.C_CATEGORY).val();\r\n");
      out.write("      var C_TAG = $(frm.C_TAG).val();\r\n");
      out.write("      var C_PIC = $(frm.C_PIC).val();\r\n");
      out.write("      var C_SPOT = $(frm.C_SPOT).val();\r\n");
      out.write("\r\n");
      out.write("      alert(C_NAME + \"\\n\" + C_TAG + \"\\n\" + C_CONDITION + \"\\n\" + C_CATEGORY + \"\\n\" + C_PCHK + \"\\n\" + C_WELCOME + \"\\n\" + C_PIC + \"\\n\" + C_SPOT);\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         type : \"post\",\r\n");
      out.write("         url : \"insert\",\r\n");
      out.write("         data : {\r\n");
      out.write("            \"c_name\" : C_NAME,\r\n");
      out.write("            \"c_pchk\" : C_PCHK,\r\n");
      out.write("            \"c_welcome\" : C_WELCOME,\r\n");
      out.write("            \"c_condition\" : C_CONDITION,\r\n");
      out.write("            \"c_category\" : C_CATEGORY,\r\n");
      out.write("            \"c_tag\" : C_TAG,\r\n");
      out.write("            \"c_pic\" : C_PIC,\r\n");
      out.write("            \"c_spot\" : C_SPOT\r\n");
      out.write("         },\r\n");
      out.write("         success : function(data) {\r\n");
      out.write("            if ($(frm.C_NAME).val() == \"\") {\r\n");
      out.write("               alert(\"동아리이름\");\r\n");
      out.write("               $(frm.C_NAME).focus();\r\n");
      out.write("            } else if ($(frm.C_TAG).val() == \"\") {\r\n");
      out.write("               alert(\"해쉬태그설정해주세요\");\r\n");
      out.write("               $(frm.C_TAG).focus();\r\n");
      out.write("            } else {\r\n");
      out.write("               if (!confirm(\"글등록?\"))\r\n");
      out.write("                  return;\r\n");
      out.write("               frm.submit();\r\n");
      out.write("            }\r\n");
      out.write("            alert(\"성공\");\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   $(frm.C_PIC).on(\"change\", function() {\r\n");
      out.write("      var file = $(frm.C_PIC)[0].files[0];\r\n");
      out.write("      $(\"#image\").attr(\"src\", URL.createObjectURL(file));\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
