/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-11-26 07:52:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>[일정수정]</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <form name =\"frm\" action=\"guget\" method=\"get\" enctype=\"multipart/form-data\">\r\n");
      out.write("   <table border=1 >\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td><input type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td >시간</td>\r\n");
      out.write("            <td>\r\n");
      out.write("                 시작날짜<input type=\"date\" name='sdate' value=\"2020-01-01\" />\r\n");
      out.write("                 시작시간:<input type='time' name='stime'/>\r\n");
      out.write("            </td>\r\n");
      out.write("            <td>\r\n");
      out.write("               종료날짜<input type='date' name='edate' value=\"2020-01-01\" min=\"2020-01-01\"/>      \r\n");
      out.write("               종료시간:<input type='time' name='etime'/>      \r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>일정이름:</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"cal_title\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>일정분류:</td>\r\n");
      out.write("            <td>\r\n");
      out.write("               <select name=\"cal_sdchk\">\r\n");
      out.write("                  <option>개인일정</option>\r\n");
      out.write("                  <option>모임일정</option>\r\n");
      out.write("                  <option>1</option>\r\n");
      out.write("                  <option>2</option>\r\n");
      out.write("                  <option>3</option>\r\n");
      out.write("               </select>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td >컨텐츠:</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"cal_content\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>일정위치</td>\r\n");
      out.write("            <td><input type=\"text\" name=\"cal_place\"></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>일정공유여부:</td>\r\n");
      out.write("            <td>\r\n");
      out.write("                 y:<input type=\"radio\" name=\"cal_schk\" value=\"y\">\r\n");
      out.write("                  n:<input type=\"radio\" name=\"cal_schk\" value=\"n\">\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td colspan=2>\r\n");
      out.write("                 <input type=\"submit\" value=\"완료\"/>\r\n");
      out.write("               <a href=\"/home\"><input type=\"reset\" value=\"취소\"></a>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("     </form> \r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("e.preventDefault();\r\n");
      out.write("$(frm).submit(function(e){\r\n");
      out.write("      var cal_sdate=($(frm.sdate).val()+ \" \" + $(frm.stime).val());\r\n");
      out.write("      var cal_edate=($(frm.edate).val()+ \" \" + $(frm.etime).val());\r\n");
      out.write("      var cal_title=$(frm.cal_title).val();\r\n");
      out.write("      var cal_sdchk=$(frm.cal_sdchk).val();\r\n");
      out.write("      var cal_content=$(frm.cal_content).val();\r\n");
      out.write("      var cal_place=$(frm.cal_place).val();\r\n");
      out.write("      var cal_schk=$(frm.cal_schk).val();\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      alert(cal_sdate+cal_edate+cal_title+cal_title\r\n");
      out.write("            +cal_sdchk+cal_content+cal_place+\r\n");
      out.write("            cal_schk);\r\n");
      out.write("      \r\n");
      out.write("      $.ajax({\r\n");
      out.write("         type:\"get\",\r\n");
      out.write("         url:\"/guget\",\r\n");
      out.write("         data:{\"id\":id ,\"cal_sdate\":cal_sdate ,\"cal_edate\":cal_edate , \"cal_title\":cal_title,\r\n");
      out.write("            \"cal_sdchk\":cal_sdchk,\"cal_content\":cal_content,\"cal_place\":cal_place,\r\n");
      out.write("            \"cal_schk\":cal_schk},\r\n");
      out.write("         success:function(data){\r\n");
      out.write("               alert(\"모임만들기 성공\");\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("    \r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
