/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-28 07:32:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1605611870166L));
    _jspx_dependants.put("jar:file:/D:/Spring%20WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/Spring%20WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FP/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   \r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("   <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("   <script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("   <script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/popup.css\">\r\n");
      out.write("   <title>final project</title>\r\n");
      out.write("   <style>\r\n");
      out.write("      @import url(https://fonts.googleapis.com/css?family=Open+Sans);   \r\n");
      out.write("      .search {\r\n");
      out.write("         width: 100%;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            display: flex;\r\n");
      out.write("      }   \r\n");
      out.write("      .searchTerm {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border: 3px solid #00B4CC;\r\n");
      out.write("            border-right: none;\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("            height: 20px;\r\n");
      out.write("            border-radius: 5px 0 0 5px;\r\n");
      out.write("            outline: none;\r\n");
      out.write("        }   \r\n");
      out.write("        .searchButton {\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 36px;\r\n");
      out.write("            border: 1px solid #00B4CC;\r\n");
      out.write("            background: #00B4CC;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border-radius: 0 5px 5px 0;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        /*Resize the wrap to see the search bar change!*/\r\n");
      out.write("        .wrap2 {\r\n");
      out.write("            width: 30%;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            margin-top: 150px;\r\n");
      out.write("        }\r\n");
      out.write("        .select2 {\r\n");
      out.write("            border: 3px solid #00B4CC;\r\n");
      out.write("            padding: 5px;\r\n");
      out.write("            height: 35px;\r\n");
      out.write("            border-radius: 5px 5px 5px 5px;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            margin-right:20px;\r\n");
      out.write("        }\r\n");
      out.write("        .icon2{\r\n");
      out.write("        width: 150px;\r\n");
      out.write("        height: 170px;\r\n");
      out.write("        }\r\n");
      out.write("   </style>   \r\n");
      out.write("</head>\r\n");
      out.write("      <body>\r\n");
      out.write("      <div>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("</div>\r\n");
      out.write("   \r\n");
      out.write("      <!-- 조원소개를 넣으면 어떨까? 12-18-->\r\n");
      out.write("      <main class=\"content\">\r\n");
      out.write("         <section class=\"services my_container clearfix\">\r\n");
      out.write("            <div class=\"service_item\">\r\n");
      out.write("               <span class=\"icon\"><img class=\"icon2\" src=\"display?fileName=김선관.jpg\"></span>\r\n");
      out.write("               <h4>김선관</h4>\r\n");
      out.write("               <p>\r\n");
      out.write("\t\t\t\t     회의 진행, 일정 조율 <br>\r\n");
      out.write("\t\t\t\t  JSP, Controller<br>\r\n");
      out.write("\t\t\t\t  CSS, JSP 결합\r\n");
      out.write("               </p>\r\n");
      out.write("               <span class=\"status\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"service_item\">\r\n");
      out.write("               <span class=\"icon\"><img class=\"icon2\" src=\"display?fileName=조새벽.jpg\"></span>\r\n");
      out.write("               <h4>조새벽</h4>\r\n");
      out.write("               <p>\r\n");
      out.write("\t\t\t\t    회의 정리 및 일정 공유 <br>\r\n");
      out.write("\t\t\t\t JSP, fullCalender<br>\r\n");
      out.write("\t\t\t\t  유효성 검토\r\n");
      out.write("               </p>\r\n");
      out.write("               <span class=\"status\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"service_item\">\r\n");
      out.write("               <span class=\"icon\"><img class=\"icon2\" src=\"display?fileName=전영진.jpg\"></span>\r\n");
      out.write("               <h4>전영진</h4>\r\n");
      out.write("               <p>\r\n");
      out.write("\t\t\t\t     스토리 보드 작성 <br>\r\n");
      out.write("\t\t\t\t  CSS , JSP<br>\r\n");
      out.write("\t\t\t\t  정적 CSS 전담\r\n");
      out.write("               </p>\r\n");
      out.write("               <span class=\"status\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"service_item\">\r\n");
      out.write("               <span class=\"icon\"><img class=\"icon2\" src=\"display?fileName=최대식.jpg\"></span>\r\n");
      out.write("               <h4>최대식</h4>\r\n");
      out.write("               <p>\r\n");
      out.write("\t\t\t\t    DB 설계 및 기입 <br>\r\n");
      out.write("\t\t\t\t  Controller, DB<br>\r\n");
      out.write("\t\t\t\t Service, Model\r\n");
      out.write("               </p>\r\n");
      out.write("               <span class=\"status\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"service_item\">\r\n");
      out.write("               <span class=\"icon\"><img class=\"icon2\" src=\"display?fileName=이장희.jpg\"></span>\r\n");
      out.write("               <h4>이장희</h4>\r\n");
      out.write("               <p>\r\n");
      out.write("\t\t\t\t    스토리 보드 작성 <br>\r\n");
      out.write("\t\t\t\t JSP , fullCalender <br>\r\n");
      out.write("\t\t\t\t유효성 검토\r\n");
      out.write("               </p>\r\n");
      out.write("               <span class=\"status\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"service_item\">\r\n");
      out.write("               <span class=\"icon\"><img class=\"icon2\" src=\"display?fileName=안동현.jpg\"></span>\r\n");
      out.write("               <h4>안동현</h4>\r\n");
      out.write("               <p>\r\n");
      out.write("\t\t\t\t    스토리 보드 작성 <br>\r\n");
      out.write("\t\t\t\t CSS 전체 구상 및 구현<br>\r\n");
      out.write("\t\t\t\t동적 CSS 전담\r\n");
      out.write("               </p>\r\n");
      out.write("               <span class=\"status\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("         </section><!--//services -->\r\n");
      out.write("   </main>  \r\n");
      out.write("    <div style=\"\">  \r\n");
      out.write("      <!-- 내가 가입한  동아리 -->\r\n");
      out.write("       ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         <!-- 검색 -->\r\n");
      out.write("         <div class=\"wrap2\">   \r\n");
      out.write("            <div class=\"search\">\r\n");
      out.write("               <select class=\"select2\">\r\n");
      out.write("                   <option value=\"c_name\">동아리 이름</option>\r\n");
      out.write("               </select>\r\n");
      out.write("            <input type=\"text\" class=\"searchTerm\" id=\"keyword\">\r\n");
      out.write("              <button type=\"button\" class=\"searchButton\" id=\"btnSearch\"><i class=\"fa fa-search\"></i></button>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      <!-- 검색 결과 나오기 -->\r\n");
      out.write("          <table id=\"searchResult\" class=\"searchList2\"></table>\r\n");
      out.write("       <div id=\"divSearchResult\"></div>\r\n");
      out.write("         <script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("             <table>\r\n");
      out.write("                  <tr style=\"margin-bottom: 15px;\">\r\n");
      out.write("                       <th class=\"m_name\">동아리 이름</th>\r\n");
      out.write("                       <th class=\"m_pid\">개설자</th>\r\n");
      out.write("                       <th class=\"m_spot\">활동장소</th>\r\n");
      out.write("                       <th class=\"m_category\">카테고리</th> \r\n");
      out.write("                        <th class=\"m_category\">이동</th>\r\n");
      out.write("                  </tr>\r\n");
      out.write("            </table> \r\n");
      out.write("         {{#each searchList}}      \r\n");
      out.write("                 <tr style=\"margin-bottom: 15px;\">\r\n");
      out.write("                     <td class=\"m_name\">{{c_name}}</td>\r\n");
      out.write("                     <td class=\"m_pid\">{{c_pid}}</td>\r\n");
      out.write("                     <td class=\"m_spot\">{{c_spot}}</td>\r\n");
      out.write("                     <td class=\"m_category\">{{c_category}}</td>\r\n");
      out.write("                     <td class=\"m_btn\"><input type=\"button\" value=\"이동하기\" class=\"btn_m\"></td>\r\n");
      out.write("                 </tr>\r\n");
      out.write("         {{/each}}\r\n");
      out.write("         </script>\r\n");
      out.write("         <div class=\"page_wrap\">\r\n");
      out.write("            <div class=\"page_nation\" id=\"page_nation\"></div>\r\n");
      out.write("         </div>   \r\n");
      out.write("    </div>\r\n");
      out.write("        \r\n");
      out.write("      <!-- 추천 동아리 -->\r\n");
      out.write("   <div  class=\"detail\" style=\"font-size:40px; margin-top:80px;\" id=\"game_list\"><h1>게임</h1></div>    \r\n");
      out.write("      <div class=\"swiper-container\">\r\n");
      out.write("         <div class=\"swiper-wrapper\">\r\n");
      out.write("            <!-- Slides  넣을곳 -->\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"swiper-button-prev\"></div> \r\n");
      out.write("         <div class=\"swiper-button-next\"></div> \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div  class=\"detail\" style=\"font-size:40px; margin-top:80px; \"><h1>운동</h1></div>    \r\n");
      out.write("      <div class=\"swiper-container\">\r\n");
      out.write("         <div class=\"swiper-wrapper\">\r\n");
      out.write("            <!-- Slides  넣을곳 -->\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"swiper-button-prev\"></div> \r\n");
      out.write("         <div class=\"swiper-button-next\"></div> \r\n");
      out.write("     </div>\r\n");
      out.write("      \r\n");
      out.write("    <div  class=\"detail\" style=\"font-size:40px; margin-top:80px; \"><h1>공부</h1></div>    \r\n");
      out.write("      <div class=\"swiper-container\">\r\n");
      out.write("         <div class=\"swiper-wrapper\">\r\n");
      out.write("            <!-- Slides  넣을곳 -->\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"swiper-button-prev\"></div> \r\n");
      out.write("         <div class=\"swiper-button-next\"></div> \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    <div  class=\"detail\" style=\"font-size:40px; margin-top:80px; \"><h1>취미</h1></div>    \r\n");
      out.write("      <div class=\"swiper-container\">\r\n");
      out.write("         <div class=\"swiper-wrapper\">\r\n");
      out.write("            <!-- Slides  넣을곳 -->\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("         <div class=\"swiper-button-prev\"></div> \r\n");
      out.write("         <div class=\"swiper-button-next\"></div> \r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    <div  class=\"detail\" style=\"font-size:40px; margin-top:80px; \"><h1>기타</h1></div>    \r\n");
      out.write("      <div class=\"swiper-container\">\r\n");
      out.write("         <div class=\"swiper-wrapper\">\r\n");
      out.write("            <!-- Slides  넣을곳 -->\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"swiper-button-prev\"></div> \r\n");
      out.write("         <div class=\"swiper-button-next\"></div> \r\n");
      out.write("     </div>\r\n");
      out.write("   <div>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("</div>\r\n");
      out.write("   \r\n");
      out.write("   <!-- 팝업창  -->\r\n");
      out.write("   <div class=\"popup\" id=\"popup\">\r\n");
      out.write("      <div class=\"popup-inner\">\r\n");
      out.write("            <div class=\"popupimg\" id=\"c_pic\" style=\"height:100%; width:100%;\"><!-- 사진 자리  --></div>\r\n");
      out.write("           <div class=\"memo\">\r\n");
      out.write("              <h1 class=\"memoname\" id=\"c_name\"></h1>\r\n");
      out.write("               <div class=\"left\">\r\n");
      out.write("               <h2 class=\"h42\">동아리정보</h2>\r\n");
      out.write("               <div class=\"memo3\">\r\n");
      out.write("                  <ul class=\"ul2\">\r\n");
      out.write("                      <li class=\"li2\"><i class=\"fas fa-crown\" style=\"font-size: 25px; color:yellow;\"></i><span class=\"span2\" id=\"c_pid\"></span></li>\r\n");
      out.write("                        <li class=\"li2\"><i class=\"fas fa-male\" style=\"font-size: 35px; margin-left: 8px; margin-right: 13px;\"></i><span class=\"span2\" id=\"count\"></span></li>\r\n");
      out.write("                        <li class=\"li2\"><i class=\"fas fa-map-marker-alt\" style=\"font-size: 25px; margin-left: 5px; margin-right: 5px;\"></i><span class=\"span2\" id=\"c_spot\"></span></li>\r\n");
      out.write("                        <li class=\"li2\"><i class=\"far fa-calendar-check\" style=\"font-size: 21px; margin-left: 5px; margin-right: 5px;\"></i><span class=\"span2\" id=\"c_regdate\"></span></li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("         </div>\r\n");
      out.write("           <div class=\"rigth\">\r\n");
      out.write("               <h2 class=\"h42\">가입조건</h2>         \r\n");
      out.write("               <div class=\"memo2\">\r\n");
      out.write("                     <ul class=\"ul2\">\r\n");
      out.write("                        <li class=\"li2\">\r\n");
      out.write("                           <span class=\"span2\" id=\"c_condition\"></span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                     </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("           <div class=\"footer\">\r\n");
      out.write("                 <h2 class=\"h43\">소개하기</h2>\r\n");
      out.write("                 <div class=\"memo4\">\r\n");
      out.write("                     <p class=\"p2\" id=\"c_welcome\"></p>\r\n");
      out.write("                </div>\r\n");
      out.write("           </div>\r\n");
      out.write("      </div>         \r\n");
      out.write("           <a class=\"popup__close\" id=\"close\">X</a>\r\n");
      out.write("           <input class=\"btncl\" type=\"button\" value=\"이동하기\" id=\"joinClub\">\r\n");
      out.write("       </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("   // 추천 동아리 슬라이더 효과를 jscript를 통해 준다\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("       var swiper = new Swiper(\".swiper-container\", {\r\n");
      out.write("            effect : \"coverflow\", // 커버플로우 효과 사용\r\n");
      out.write("            grabCursor : true,\r\n");
      out.write("            centeredSlides : true,\r\n");
      out.write("            loop : true, // 슬라이드 반복\r\n");
      out.write("            slidesPerView : \"auto\",\r\n");
      out.write("            coverflowEffect : {\r\n");
      out.write("               rotate : 0, // 슬라이더 회전 각 : 클수록 슬라이딩시 회전이 커짐\r\n");
      out.write("                  stretch : -50, // 슬라이더간 거리(픽셀) : 클수록 슬라이더가 서로 많이 겹침\r\n");
      out.write("                  depth : 0, // 깊이 효과값 : 클수록 멀리있는 느낌이 강해짐\r\n");
      out.write("                  modifier : 1, // 효과 배수 : 위 숫자값들에 이 값을 곱하기 처리하여 효과를 강하게 처리함\r\n");
      out.write("                  slideShadows : false\r\n");
      out.write("               // 슬라이더 그림자 : 3D 효과를 강조하기 위한 회전시 흐릿한 효과\r\n");
      out.write("            },\r\n");
      out.write("            speed : 500,// 슬라이드 속도 2초\r\n");
      out.write("            navigation : {\r\n");
      out.write("                  nextEl : '.swiper-button-next', // 다음 버튼 클래스명\r\n");
      out.write("                  prevEl : '.swiper-button-prev', // 이번 버튼 클래스명\r\n");
      out.write("            },\r\n");
      out.write("            pagination : {\r\n");
      out.write("            el : \".swiper-pagination\"\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   });\r\n");
      out.write("    \r\n");
      out.write("    //내가 가입한 동아리 슬라이더 효과를 jscript를 통해 준다\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("       var swiper = new Swiper(\".swiper-container2\", {\r\n");
      out.write("            effect : \"coverflow\", // 커버플로우 효과 사용\r\n");
      out.write("            grabCursor : true,\r\n");
      out.write("            centeredSlides : true,\r\n");
      out.write("            loop : false, // 슬라이드 반복\r\n");
      out.write("            slidesPerView : \"auto\",\r\n");
      out.write("            coverflowEffect : {\r\n");
      out.write("               rotate : 0, // 슬라이더 회전 각 : 클수록 슬라이딩시 회전이 커짐\r\n");
      out.write("                  stretch : -50, // 슬라이더간 거리(픽셀) : 클수록 슬라이더가 서로 많이 겹침\r\n");
      out.write("                  depth : 0, // 깊이 효과값 : 클수록 멀리있는 느낌이 강해짐\r\n");
      out.write("                  modifier : 1, // 효과 배수 : 위 숫자값들에 이 값을 곱하기 처리하여 효과를 강하게 처리함\r\n");
      out.write("                  slideShadows : false\r\n");
      out.write("               // 슬라이더 그림자 : 3D 효과를 강조하기 위한 회전시 흐릿한 효과\r\n");
      out.write("            },\r\n");
      out.write("            speed : 500,// 슬라이드 속도 0.5초\r\n");
      out.write("            navigation : {\r\n");
      out.write("                  nextEl : '.swiper-button-next', // 다음 버튼 클래스명\r\n");
      out.write("                  prevEl : '.swiper-button-prev', // 이번 버튼 클래스명\r\n");
      out.write("            },\r\n");
      out.write("            pagination : {\r\n");
      out.write("            el : \".swiper-pagination\"\r\n");
      out.write("         }\r\n");
      out.write("      });\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("    // 추천 동아리를 클릭했을때 popup이 뜬다. 해당 popup에 정보를 입력시킨다.\r\n");
      out.write("    var c_code =\"\";\r\n");
      out.write("   $(\".imgc\").on(\"click\",function(){\r\n");
      out.write("      c_code = $(this).attr(\"c_code\");\r\n");
      out.write("      $.ajax({\r\n");
      out.write("         type : \"get\",\r\n");
      out.write("         url : \"readClub\",\r\n");
      out.write("         data : {\"c_code\":c_code},\r\n");
      out.write("         dataType : \"json\",\r\n");
      out.write("         success : function(data) {\r\n");
      out.write("            $(\"#c_pic\").html(\"<img class='popupimgc' src='display?fileName=\" + data.cvo.c_pic + \"'>\");\r\n");
      out.write("            $(\"#c_pid\").text(data.cvo.c_pid);\r\n");
      out.write("            $(\"#count\").text(data.maincount);\r\n");
      out.write("            $(\"#c_spot\").text(data.cvo.c_spot);\r\n");
      out.write("            $(\"#c_regdate\").text(data.cvo.c_regdate);\r\n");
      out.write("            $(\"#c_condition\").text(data.cvo.c_condition);\r\n");
      out.write("            $(\"#c_welcome\").text(data.cvo.c_welcome);\r\n");
      out.write("            $(\"#c_name\").text(data.cvo.c_name);\r\n");
      out.write("         }\r\n");
      out.write("      })\r\n");
      out.write("    });\r\n");
      out.write("   \r\n");
      out.write("    // popup을 없앤다.\r\n");
      out.write("   $(document).ready(function() {\r\n");
      out.write("      $(\"#close\").click(function(){            \r\n");
      out.write("         window.history.back()       \r\n");
      out.write("      });       \r\n");
      out.write("   });\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    // popup에서 이동하기 button을 누르면 해당 동아리 page로 이동시킨다. \r\n");
      out.write("   $(\"#joinClub\").click(function(){ \r\n");
      out.write("      location.href=\"club_first?c_code=\"+c_code; \r\n");
      out.write("   });  \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    var page = 1;\r\n");
      out.write("    var keyword = $(\"#keyword\").val();\r\n");
      out.write("   // 검색 결과가 나오는 div를 숨긴다.  \r\n");
      out.write("   $(\"#divSearchResult\").hide();\r\n");
      out.write("   \r\n");
      out.write("   // 동아리 검색 결과를 ajax을 통해 보여준다. \r\n");
      out.write("    $(\"#btnSearch\").on(\"click\",function(){\r\n");
      out.write("       keyword = $(\"#keyword\").val();\r\n");
      out.write("       \r\n");
      out.write("       getSearchResult();\r\n");
      out.write("       \r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("     //페이지네이션\r\n");
      out.write("   $(\"#page_nation\").on(\"click\",\"a\",function(e){\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        page=$(this).attr(\"href\");\r\n");
      out.write("        \r\n");
      out.write("        getSearchResult();\r\n");
      out.write("     });\r\n");
      out.write("     \r\n");
      out.write("     //검색 결과를 가져오는 기능을 하는 함수를 만든다.\r\n");
      out.write("   function getSearchResult(){\r\n");
      out.write("        $.ajax({\r\n");
      out.write("          type : \"get\",\r\n");
      out.write("         url : \"searchcir\",\r\n");
      out.write("         data : {\"keyword\":keyword,\"page\":page},\r\n");
      out.write("         dataType : \"json\",\r\n");
      out.write("         success:function(data) {\r\n");
      out.write("            \tvar temp=Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("                 $(\"#searchResult\").html(temp(data));\r\n");
      out.write("                 \r\n");
      out.write("                 if(data.pm.totalCount=='0'){\r\n");
      out.write(" \t\t        \t$(\"#divSearchResult\").html(\"검색결과가 없습니다\");\r\n");
      out.write(" \t\t        }\r\n");
      out.write("                 \r\n");
      out.write("                 var str=\"\";\r\n");
      out.write("                 if(data.pm.prev){\r\n");
      out.write("                    str += \"<a href='\"+ (data.pm.startPage-1) +\"'>◀</a>\"\r\n");
      out.write("                 }       \r\n");
      out.write("                 for(var i=data.pm.startPage; i<=data.pm.endPage; i++){\r\n");
      out.write("                    if(page==i){\r\n");
      out.write("                       str += \"[<a href='\"+ i +\"' class='active'>\" + i +\"</a>]\";\r\n");
      out.write("                    }else{\r\n");
      out.write("                       str += \"[<a href='\"+ i +\"'>\" + i +\"</a>]\";\r\n");
      out.write("                    }\r\n");
      out.write("            }\r\n");
      out.write("                if(data.pm.next){\r\n");
      out.write("                  str += \"<a href='\"+ (data.pm.endPage+1) +\"'>▶</a>\"\r\n");
      out.write("               }\r\n");
      out.write("                $(\"#page_nation\").html(str);\r\n");
      out.write("                \r\n");
      out.write("         }\r\n");
      out.write("       });\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/main.jsp(130,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty myList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write(" \r\n");
        out.write("         <div  class=\"detail\" style=\"font-size:40px; margin-top:80px; margin-bottom:50px;\"><h1>가입한동아리</h1></div>    \r\n");
        out.write("               <div class=\"swiper-container2\" >\r\n");
        out.write("                  <div class=\"swiper-wrapper\">\r\n");
        out.write("                     <!-- Slides  넣을곳 -->\r\n");
        out.write("                        ");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                  </div>\r\n");
        out.write("            <div class=\"swiper-button-prev\"></div> \r\n");
        out.write("             <div class=\"swiper-button-next\"></div> \r\n");
        out.write("            </div>\r\n");
        out.write("         ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /WEB-INF/views/main.jsp(135,24) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main.jsp(135,24) '${myList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${myList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/main.jsp(135,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("mylist");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                              <div class=\"swiper-slide\">\r\n");
          out.write("                                 <div class=\"picture\">  \r\n");
          out.write("                                    <a class=\"button2\" href=\"club_first?c_code=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mylist.c_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">              \r\n");
          out.write("                                        <img class=\"imgc\" src=\"display?fileName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mylist.c_pic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" c_code=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mylist.c_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                                    </a> \r\n");
          out.write("                                    <div class=detail>\r\n");
          out.write("                                        <h3>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mylist.c_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h3>\r\n");
          out.write("                                     </div>\r\n");
          out.write("                                  </div>\r\n");
          out.write("                            </div>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /WEB-INF/views/main.jsp(195,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main.jsp(195,12) '${gameList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${gameList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/main.jsp(195,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("glist");
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  <div class=\"swiper-slide\">\r\n");
          out.write("                     <div class=\"picture\">  \r\n");
          out.write("                        <a class=\"button2\" href=\"#popup\">              \r\n");
          out.write("                            <img class=\"imgc\" src=\"display?fileName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${glist.c_pic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" c_code=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${glist.c_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                        </a> \r\n");
          out.write("                        <div class=detail>\r\n");
          out.write("                            <h3>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${glist.c_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h3>\r\n");
          out.write("                      </div>\r\n");
          out.write("                   </div>\r\n");
          out.write("                </div>\r\n");
          out.write("           ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f2.setParent(null);
    // /WEB-INF/views/main.jsp(216,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main.jsp(216,12) '${sportList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${sportList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/main.jsp(216,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f2.setVar("splist");
    int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
      if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  <div class=\"swiper-slide\">\r\n");
          out.write("                     <div class=\"picture\">   \r\n");
          out.write("                  <a class=\"button2\" href=\"#popup\">                 \r\n");
          out.write("                           <img class=\"imgc\" src=\"display?fileName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${splist.c_pic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"  c_code=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${splist.c_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                        </a>                   \r\n");
          out.write("                        <div class=detail>\r\n");
          out.write("                            <h3>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${splist.c_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h3>\r\n");
          out.write("                         </div>\r\n");
          out.write("                      </div>\r\n");
          out.write("                </div>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f2.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f3.setParent(null);
    // /WEB-INF/views/main.jsp(237,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main.jsp(237,12) '${studyList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${studyList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/main.jsp(237,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f3.setVar("stlist");
    int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
      if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  <div class=\"swiper-slide\">\r\n");
          out.write("                     <div class=\"picture\">   \r\n");
          out.write("                       <a class=\"button2\" href=\"#popup\">                 \r\n");
          out.write("                           <img class=\"imgc\" src=\"display?fileName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stlist.c_pic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"  c_code=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stlist.c_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                        </a>               \r\n");
          out.write("                        <div class=detail>\r\n");
          out.write("                            <h3>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${stlist.c_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h3>\r\n");
          out.write("                         </div>\r\n");
          out.write("                   </div>\r\n");
          out.write("                </div>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f3.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f4.setParent(null);
    // /WEB-INF/views/main.jsp(258,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f4.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main.jsp(258,12) '${hobbyList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${hobbyList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/main.jsp(258,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f4.setVar("holist");
    int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
      if (_jspx_eval_c_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  <div class=\"swiper-slide\">\r\n");
          out.write("                     <div class=\"picture\">  \r\n");
          out.write("                        <a class=\"button2\" href=\"#popup\">                 \r\n");
          out.write("                            <img class=\"imgc\" src=\"display?fileName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${holist.c_pic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"  c_code=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${holist.c_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                        </a>               \r\n");
          out.write("                        <div class=detail>\r\n");
          out.write("                           <h3>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${holist.c_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h3>\r\n");
          out.write("                         </div>\r\n");
          out.write("                      </div>\r\n");
          out.write("                  </div>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f4.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f5 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f5.setParent(null);
    // /WEB-INF/views/main.jsp(279,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f5.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/main.jsp(279,12) '${etcList}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${etcList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/main.jsp(279,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f5.setVar("etclist");
    int[] _jspx_push_body_count_c_005fforEach_005f5 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f5 = _jspx_th_c_005fforEach_005f5.doStartTag();
      if (_jspx_eval_c_005fforEach_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  <div class=\"swiper-slide\">\r\n");
          out.write("                   <div class=\"picture\"> \r\n");
          out.write("                        <a class=\"button2\" href=\"#popup\">                 \r\n");
          out.write("                           <img class=\"imgc\" src=\"display?fileName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${etclist.c_pic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"  c_code=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${etclist.c_code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                        </a>                 \r\n");
          out.write("                        <div class=detail>\r\n");
          out.write("                            <h3>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${etclist.c_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h3>\r\n");
          out.write("                         </div>\r\n");
          out.write("                      </div>\r\n");
          out.write("                </div>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f5[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f5.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f5.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f5);
    }
    return false;
  }
}
