/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-28 06:58:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class makeGroup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1605611870166L));
    _jspx_dependants.put("jar:file:/D:/Spring%20WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/make.css\" />\r\n");
      out.write("<title>모임 만들기</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("</div>\r\n");
      out.write("   <h1 class=\"clupMake-hedder\">모임 만들기</h1>\r\n");
      out.write("   <div class=\"SectionCreateCafe CreateCafe\">\r\n");
      out.write("      <form action=\"makeGroupPost\" method=\"post\" name=\"frm\" enctype=\"multipart/form-data\">\r\n");
      out.write("         <table class=\"cafe_input\">\r\n");
      out.write("            <colgroup>\r\n");
      out.write("               <col width=\"114\">\r\n");
      out.write("               <col width=\"545\">\r\n");
      out.write("            </colgroup>\r\n");
      out.write("            <tbody>\r\n");
      out.write("               <tr class=\"cafe_name\">\r\n");
      out.write("                  <th scope=\"row\">\r\n");
      out.write("                     <h2 class=\"makeClupH2\">모임 이름</h2>\r\n");
      out.write("                  </th>\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <div class=\"input_area\">\r\n");
      out.write("                        <div class=\"FormInputText\" >\r\n");
      out.write("                           <input type=\"text\" class=\"input_text input_txt\" name=\"g_name\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"txt\">모임이름 을 정해주세요.</p>   \r\n");
      out.write("                     </div>\r\n");
      out.write("                  </td>\r\n");
      out.write("               </tr>\r\n");
      out.write("               <tr class=\"cafe_keyword\">\r\n");
      out.write("                  <th scope=\"row\">\r\n");
      out.write("                      <h2 class=\"makeClupH2\">모임 비밀번호</h2>\r\n");
      out.write("                  </th>\r\n");
      out.write("                  <td>\r\n");
      out.write("                     <div class=\"SectionCreateCafeKeyword\">                     \r\n");
      out.write("                        <div class=\"cafe_keyword_input_area\">\r\n");
      out.write("                           <div class=\"FormInputText\">\r\n");
      out.write("                              <input type=\"password\" class=\"input_text input_txt2\" name=\"g_pass\">                           \r\n");
      out.write("                           </div>                                             \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"txt\">8~16자 영문 대 소문자, 숫자, 특수문자를 사용하세요.</p>                     \r\n");
      out.write("                     </div>                  \r\n");
      out.write("                   </td>\r\n");
      out.write("               </tr>                     \r\n");
      out.write("               <tr>\r\n");
      out.write("                         <th scope=\"row\">\r\n");
      out.write("                         <h2 class=\"makeClupH2\">메인사진</h2>\r\n");
      out.write("                      </th>\r\n");
      out.write("                         <td width=500>\r\n");
      out.write("                           <img src=\"http://placehold.it/150x120\" id=\"image\" width=150> \r\n");
      out.write("                           <input type=\"file\" name=\"file\" class=\"imgSel\">\r\n");
      out.write("                        </td>\r\n");
      out.write("                   </tr>                               \r\n");
      out.write("            </tbody>\r\n");
      out.write("         </table>\r\n");
      out.write("         <div class=\"buttonMake\">      \r\n");
      out.write("             <input type=\"button\" value=\"취소\" class=\"btnDel\" id=\"return\">\r\n");
      out.write("             <input type=\"submit\" value=\"개설하기\" class=\"btnSave\">     \r\n");
      out.write("          </div>\r\n");
      out.write("       </form>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("   // 뒤로가기  \r\n");
      out.write("   $(document).ready(function() {\r\n");
      out.write("      $(\"#return\").click(function(){            \r\n");
      out.write("         window.history.back()       \r\n");
      out.write("      });       \r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("   // 사진\r\n");
      out.write("   $(frm.file).on(\"change\", function() {\r\n");
      out.write("      var file = $(frm.file)[0].files[0];\r\n");
      out.write("       $(\"#image\").attr(\"src\", URL.createObjectURL(file));\r\n");
      out.write("   });\r\n");
      out.write("   $(frm.file).hide();\r\n");
      out.write("   $(\"#image\").on(\"click\", function() {\r\n");
      out.write("      $(frm.file).click();\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   //submit \r\n");
      out.write("   $(frm).submit(function(e) {\r\n");
      out.write("      e.preventDefault();\r\n");
      out.write("       var g_name = $(frm.g_name).val();\r\n");
      out.write("       var g_pass = $(frm.g_pass).val();\r\n");
      out.write("         \r\n");
      out.write("       var num = g_pass.search(/[0-9]/g);\r\n");
      out.write("       var eng = g_pass.search(/[a-z]/ig);\r\n");
      out.write("       var spe = g_pass.search(/[`~!@@#$%^&*|₩₩₩'₩\";:₩/?]/gi);\r\n");
      out.write("       var file = $(frm.file)[0].files[0];\r\n");
      out.write("       \r\n");
      out.write("       if ($(frm.g_name).val() == \"\") {\r\n");
      out.write("          alert(\"제목을 입력해주세요\");\r\n");
      out.write("           $(frm.g_name).focus();\r\n");
      out.write("           return false;\r\n");
      out.write("      }else if ($(frm.g_pass).val() == \"\") {\r\n");
      out.write("           alert(\"비밀번호를 입력해주세요\");\r\n");
      out.write("           $(frm.g_pass).focus();\r\n");
      out.write("           return false;\r\n");
      out.write("       }else if(g_pass.length < 8 || g_pass.length > 20){\r\n");
      out.write("           alert(\"8자리 ~ 20자리 이내로 입력해주세요.\");\r\n");
      out.write("           return false;\r\n");
      out.write("       }else if(g_pass.search(/\\s/) != -1){\r\n");
      out.write("           alert(\"비밀번호는 공백 없이 입력해주세요.\");\r\n");
      out.write("           return false;\r\n");
      out.write("       }else if(num < 0 || eng < 0 || spe < 0 ){\r\n");
      out.write("           alert(\"영문,숫자, 특수문자를 혼합하여 입력해주세요.\");\r\n");
      out.write("           return false;\r\n");
      out.write("       } else if ($(frm.file).val() == \"\") {\r\n");
      out.write("            alert(\"모임에 사용할 사진을 입력해주세요\");\r\n");
      out.write("           $(frm.g_pass).focus();\r\n");
      out.write("           return false;\r\n");
      out.write("       } else {\r\n");
      out.write("           if (!confirm(\"모임을 만드시겟습니까?\")) return;\r\n");
      out.write("           frm.submit();\r\n");
      out.write("      }\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
