/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-06 07:22:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class makemnotice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1605611870166L));
    _jspx_dependants.put("jar:file:/D:/Spring%20WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/Spring%20WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FP/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>고객센터 이벤트 insert</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<button onClick=\"location.href='/'\">홈으로</button>\r\n");
      out.write("\t<button onClick=\"location.href='Service'\">공지사항</button>\r\n");
      out.write("\t<button onClick=\"location.href='Event'\">이벤트</button>\r\n");
      out.write("\t<button onClick=\"location.href='QnA'\">Q&A</button>\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<h1>고객센터 공지사항 insert</h1>\r\n");
      out.write("\t\t<form action=\"mninsert\" method=\"post\" name=\"frm\">\r\n");
      out.write("\t\t\t<table border=1>\r\n");
      out.write("<!-- \t\t\t<tr> -->\r\n");
      out.write("<!--          \t\t<td width=150>카테고리</td> -->\r\n");
      out.write("<!--          \t\t<td> -->\r\n");
      out.write("<!--          \t\t\t<select name = \"n_kg\"> -->\r\n");
      out.write("<!--          \t\t\t\t<option value=\"notice\">공지</option> -->\r\n");
      out.write("<!--          \t\t\t\t<option value=\"QnA\">Q&A</option> -->\r\n");
      out.write("<!--          \t\t\t\t<option value=\"Event\">Event</option> -->\r\n");
      out.write("<!--          \t\t\t</select> -->\r\n");
      out.write("<!--          \t\t</td> -->\r\n");
      out.write("<!--          \t</tr> -->\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=100>Title</td>\r\n");
      out.write("\t\t\t\t\t<td width=500><input type=\"text\" name=\"n_title\" width=100 maxlength=\"25\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=100>Writer</td>\r\n");
      out.write("\t\t\t\t\t<td width=500><input type=\"text\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td width=100>Content</td>\r\n");
      out.write("\t\t\t\t\t<td width=500><textarea rows=\"20\" cols=\"70\" name=\"n_content\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"n_content\">글을 입력해주세요</textarea></td>\r\n");
      out.write("\t\t\t\t</tr> \r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"저장\"> \r\n");
      out.write("\t\t\t<input type=\"reset\" value=\"취소\"> \r\n");
      out.write("\t\t\t<input type=\"button\" value=\"목록\" onClick=\"location.href='notice'\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<button onClick=\"location.href='/'\">메인페이지</button>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t//콘텐트 클릭하면 안에있는 내용 지우기\r\n");
      out.write("\tvar start = true;\r\n");
      out.write("\t$(frm.n_content).on(\"click\", function() {\r\n");
      out.write("\t   if (start) {\r\n");
      out.write("\t      $(\"#n_content\").val(\"\");\r\n");
      out.write("\t   }\r\n");
      out.write("\t   start = false;\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write(" \r\n");
      out.write("\t//서밋했을때\r\n");
      out.write("\t$(frm).submit(function(e) {\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\tvar n_title = $(frm.n_title).val();\r\n");
      out.write("\t\tvar n_content = $(frm.n_content).val();\r\n");
      out.write("\r\n");
      out.write("\t\talert(n_title+n_content);\r\n");
      out.write("\t\tif ($(frm.n_title).val() == \"\") {\r\n");
      out.write("\t\t\talert(\"제목을 입력해주세요\");\r\n");
      out.write("\t\t\t$(frm.n_title).focus();\r\n");
      out.write("\t\t} else if ($(frm.n_content).val() == \"\") {\r\n");
      out.write("\t\t\talert(\"내용을 입력해주세요\");\r\n");
      out.write("\t\t\t$(frm.n_content).focus();\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tif (!confirm(\"저장하시겠습니까?\"))\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\tfrm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
