/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-28 06:57:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPage_005fuserUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1605611870166L));
    _jspx_dependants.put("jar:file:/D:/Spring%20WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("<script   src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"  href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/make.css\"/>\r\n");
      out.write("<title>회원정보 수정</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("</div>\r\n");
      out.write("   <h1 class=\"clupMake-hedder\">회원정보 수정</h1>\r\n");
      out.write("   <div class=\"SectionCreateCafe CreateCafe\">\r\n");
      out.write("      <form action=\"myinfoUpdate\" method=\"post\" enctype=\"multipart/form-data\" name=\"frm\">\r\n");
      out.write("         <table class=\"cafe_input\">\r\n");
      out.write("            <colgroup>\r\n");
      out.write("               <col width=\"114\">\r\n");
      out.write("               <col width=\"250\">\r\n");
      out.write("            </colgroup>\r\n");
      out.write("            <tbody>\r\n");
      out.write("                  <tr class=\"cafe_keyword\">\r\n");
      out.write("                        <th scope=\"row\">\r\n");
      out.write("                            <h2 style=\"margin-top: 19px; font-size:15px; margin-left:5px;font-weight:bold; text-shadow: 0 0 1px #000;\">아이디</h2>\r\n");
      out.write("                        </th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                           <div class=\"SectionCreateCafeKeyword\">                     \r\n");
      out.write("                             <div class=\"cafe_keyword_input_area\">\r\n");
      out.write("                                <div class=\"FormInputText\">\r\n");
      out.write("                                   <input type=\"text\"class=\"input_text input_txt2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\">                                                   \r\n");
      out.write("                                </div>   \r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>               \r\n");
      out.write("                        </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"cafe_keyword\">\r\n");
      out.write("                        <th scope=\"row\">\r\n");
      out.write("                            <h2 style=\"margin-top: 19px; font-size:15px; margin-left:5px;font-weight:bold; text-shadow: 0 0 1px #000;\">비밀번호</h2>\r\n");
      out.write("                        </th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                           <div class=\"SectionCreateCafeKeyword\">                     \r\n");
      out.write("                              <div class=\"cafe_keyword_input_area\">\r\n");
      out.write("                                 <div class=\"FormInputText\">\r\n");
      out.write("                                       <input type=\"password\" name=\"pw\"  maxlength=\"20\" minlength=\"4\" class=\"input_text input_txt2\" id=\"pw\" oninput=\"checkPwd()\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userVO.pw}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <p class=\"txt\">8~16자 영문 대 소문자, 숫자, 특수문자를 사용하세요.</p>                                                                           \r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>            \r\n");
      out.write("                        </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"cafe_keyword\">\r\n");
      out.write("                        <th scope=\"row\">\r\n");
      out.write("                            <h2 style=\"margin-top: 19px; font-size:15px; margin-left:5px; font-weight:bold; text-shadow: 0 0 1px #000;\">비밀번호 확인</h2>\r\n");
      out.write("                        </th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                           <div class=\"SectionCreateCafeKeyword\">                     \r\n");
      out.write("                              <div class=\"cafe_keyword_input_area\">\r\n");
      out.write("                                 <div class=\"FormInputText\">\r\n");
      out.write("                                       <input type=\"password\" class=\"input_text input_txt2\" id=\"repwd\" oninput=\"checkPwd()\">\r\n");
      out.write("                                 </div>\r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>            \r\n");
      out.write("                        </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"cafe_keyword\">\r\n");
      out.write("                        <th scope=\"row\">\r\n");
      out.write("                            <h2 style=\"margin-top: 19px; font-size:15px; margin-left:5px;font-weight:bold; text-shadow: 0 0 1px #000;\">이름</h2>\r\n");
      out.write("                        </th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                           <div class=\"SectionCreateCafeKeyword\">                     \r\n");
      out.write("                              <div class=\"cafe_keyword_input_area\">\r\n");
      out.write("                                 <div class=\"FormInputText\">\r\n");
      out.write("                                       <input type=\"text\" name=\"name\" class=\"input_text input_txt2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userVO.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                 </div>                                                                        \r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>               \r\n");
      out.write("                      </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"cafe_keyword\">\r\n");
      out.write("                        <th scope=\"row\">\r\n");
      out.write("                            <h2 style=\"margin-top: 19px; font-size:15px; margin-left:5px;font-weight:bold; text-shadow: 0 0 1px #000;\">전화번호</h2>\r\n");
      out.write("                        </th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                           <div class=\"SectionCreateCafeKeyword\">                     \r\n");
      out.write("                              <div class=\"cafe_keyword_input_area\">\r\n");
      out.write("                                 <div class=\"FormInputText\">\r\n");
      out.write("                                 <input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userVO.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"hiddenPhone\">             \r\n");
      out.write("                                 <input type=\"text\" name=\"Fphone\" class=\"input_text input_txt12\" oninput=\"makePhone()\" id=\"Fphone\">-\r\n");
      out.write("                                 <input type=\"text\" name=\"Sphone\" class=\"input_text input_txt12\" oninput=\"makePhone()\" id=\"Sphone\">-\r\n");
      out.write("                                 <input type=\"text\" name=\"Lphone\" class=\"input_text input_txt12\" oninput=\"makePhone()\" id=\"Lphone\">\r\n");
      out.write("                                 <input type=\"hidden\" name=\"phone\">\r\n");
      out.write("                                 </div>                                                                        \r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>               \r\n");
      out.write("                      </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                  <tr class=\"cafe_keyword\">\r\n");
      out.write("                        <th scope=\"row\">\r\n");
      out.write("                            <h2 style=\"margin-top: 19px; font-size:15px; margin-left:5px;font-weight:bold; text-shadow: 0 0 1px #000;\">주소</h2>\r\n");
      out.write("                        </th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                           <div class=\"SectionCreateCafeKeyword\">                     \r\n");
      out.write("                              <div class=\"cafe_keyword_input_area\">\r\n");
      out.write("                                 <div class=\"FormInputText\">\r\n");
      out.write("                                       <input type=\"text\" id=\"sample6_postcode\" placeholder=\"우편번호\" size=\"5\"> \r\n");
      out.write("                              <input type=\"button\" onclick=\"sample6_execDaumPostcode()\" value=\"우편번호 찾기\" class=\"selectPost\">\r\n");
      out.write("                              <br>\r\n");
      out.write("                              <input type=\"text\" id=\"sample6_address\" placeholder=\"주소\" name=\"addr\" required class=\"id\" oninput=\"checkId()\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userVO.addr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly>\r\n");
      out.write("                                 </div>                                                                                                   \r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>               \r\n");
      out.write("                      </td>\r\n");
      out.write("                   </tr>\r\n");
      out.write("                  <tr class=\"cafe_keyword\">\r\n");
      out.write("                        <th scope=\"row\">\r\n");
      out.write("                            <h2 style=\"margin-top: 19px; font-size:15px; margin-left:5px;font-weight:bold; text-shadow: 0 0 1px #000;\">상세주소</h2>\r\n");
      out.write("                        </th>\r\n");
      out.write("                        <td>   \r\n");
      out.write("                           <div class=\"SectionCreateCafeKeyword\">                     \r\n");
      out.write("                              <div class=\"cafe_keyword_input_area\">\r\n");
      out.write("                                 <div class=\"FormInputText\">\r\n");
      out.write("                                       <input type=\"text\" name=\"addrDetail\" class=\"input_text input_txt2\" id=\"sample6_detailAddress\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userVO.addrDetail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                 </div>\r\n");
      out.write("                                 <p class=\"txt\">상세주소를 입력해주세요.</p>                                                                        \r\n");
      out.write("                               </div>\r\n");
      out.write("                           </div>               \r\n");
      out.write("                       </td>\r\n");
      out.write("                   </tr>\r\n");
      out.write("                  <tr class=\"cafe_keyword\">\r\n");
      out.write("                        <th scope=\"row\">\r\n");
      out.write("                            <h2 style=\"margin-top: 19px; font-size:15px; margin-left:5px;font-weight:bold; text-shadow: 0 0 1px #000;\">이메일</h2>\r\n");
      out.write("                        </th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                           <div class=\"SectionCreateCafeKeyword\">                     \r\n");
      out.write("                              <div class=\"cafe_keyword_input_area\">\r\n");
      out.write("                                 <div class=\"FormInputText\">\r\n");
      out.write("                                 <input type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userVO.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"hiddenEmail\">\r\n");
      out.write("                                 <input type=\"text\" name=\"Femail\" size=\"5\" class=\"input_text input_txt2\" oninput=\"makeEmail()\" id=\"Femail\"> @ \r\n");
      out.write("                              <select style=\"font-size: 18px; height: 30px; width: 205px;\" name=\"Lemail\">\r\n");
      out.write("                                 <option value=\"@naver.com\">naver.com</option>\r\n");
      out.write("                                 <option value=\"@gmail.com\">gmail.com</option>\r\n");
      out.write("                                 <option value=\"@hanmail.net\">hanmail.net</option>\r\n");
      out.write("                                 <option value=\"@nate.com\">nate.com</option>\r\n");
      out.write("                              </select> \r\n");
      out.write("                              <input type=\"hidden\" name=\"email\">\r\n");
      out.write("                                 </div>                                                                        \r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>               \r\n");
      out.write("                      </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr class=\"cafe_keyword\">\r\n");
      out.write("                        <th scope=\"row\">\r\n");
      out.write("                            <h2 style=\"margin-top: 19px; font-size:15px; margin-left:5px;font-weight:bold; text-shadow: 0 0 1px #000;\">키워드</h2>\r\n");
      out.write("                        </th>\r\n");
      out.write("                        <td>\r\n");
      out.write("                           <div class=\"SectionCreateCafeKeyword\">                     \r\n");
      out.write("                              <div class=\"cafe_keyword_input_area\">\r\n");
      out.write("                                 <div class=\"FormInputText\">\r\n");
      out.write("                                       <input type=\"text\"class=\"input_text input_txt2\" name=\"u_keyword\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userVO.u_keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                 </div>                                                                        \r\n");
      out.write("                              </div>\r\n");
      out.write("                           </div>               \r\n");
      out.write("                        </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                        <th scope=\"row\">\r\n");
      out.write("                            <h2 style=\"margin-top: 19px; font-size:15px; margin-left:5px;font-weight:bold; text-shadow: 0 0 1px #000;\">메인사진</h2>\r\n");
      out.write("                      </th>\r\n");
      out.write("                      <td width=500>\r\n");
      out.write("                            <input type=\"file\" name=\"file\" class=\"imgSel\">\r\n");
      out.write("                            <img src=\"display?fileName=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userVO.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"image\" width=150> \r\n");
      out.write("                            \r\n");
      out.write("                      </td>\r\n");
      out.write("                  </tr>                            \r\n");
      out.write("            </tbody>\r\n");
      out.write("         </table>\r\n");
      out.write("         <div class=\"buttonUser\">\r\n");
      out.write("            <input type=\"button\" value=\"취소\" class=\"btnCancel\" id=\"return\">\r\n");
      out.write("            <input type=\"button\" value=\"회원탈퇴\" class=\"btnDel\" onclick=\"location.href='removeUser'\">\r\n");
      out.write("             <input type=\"submit\" value=\"수정\" class=\"btnSave\" id=\"btnSave\">\r\n");
      out.write("          </div>\r\n");
      out.write("      </form>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div>\r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("   </div>                               \r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\t//메일 나눠서 받아오기\r\n");
      out.write("    var mail = $(\"#hiddenEmail\").val().split('@');\r\n");
      out.write("    $(\"#Femail\").val(mail[0]);\r\n");
      out.write("    \r\n");
      out.write("    //전화번호 나눠서 받아오기\r\n");
      out.write("    var phone = $(\"#hiddenPhone\").val().split('-');\r\n");
      out.write("    $(\"#Fphone\").val(phone[0]);\r\n");
      out.write("    $(\"#Sphone\").val(phone[1]);\r\n");
      out.write("    $(\"#Lphone\").val(phone[2]);\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("   // 뒤로가기\r\n");
      out.write("   $(document).ready(function() {\r\n");
      out.write("      $(\"#return\").click(function(){            \r\n");
      out.write("         window.history.back()       \r\n");
      out.write("      });       \r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("   //이미지받기\r\n");
      out.write("   \t$(frm.files).hide();\r\n");
      out.write("\t$(frm.file).hide();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#image\").on(\"click\",function(){\r\n");
      out.write("\t\t$(frm.file).click();\r\n");
      out.write("\t});\r\n");
      out.write("\t$(frm.files).on(\"change\",function(){\r\n");
      out.write("\t\tvar files=$(frm.files)[0].files;\r\n");
      out.write("\t\tvar str=\"\";\r\n");
      out.write("\t\t$.each(files,function(index,file){\r\n");
      out.write("\t\t\tstr+= \"<img src='\" + URL.createObjectURL(file) + \"'>\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#listFile\").html(str);\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(frm.file).on(\"change\",function(){\r\n");
      out.write("\t\tvar file=$(frm.file)[0].files[0];\r\n");
      out.write("\t\t$(\"#image\").attr(\"src\",URL.createObjectURL(file));\r\n");
      out.write("\t});\r\n");
      out.write("   \r\n");
      out.write("\t//핸드폰, 메일 합치기\r\n");
      out.write("\t\tfunction makePhone(){\r\n");
      out.write("\t      var phone = $(frm.Fphone).val() + \"-\" + $(frm.Sphone).val() + \"-\" + $(frm.Lphone).val();\r\n");
      out.write("\t      $(frm.phone).val(phone);\r\n");
      out.write("\t   }\r\n");
      out.write("\t   \r\n");
      out.write("\t   function makeEmail(){\r\n");
      out.write("\t      var email = $(frm.Femail).val() + $(frm.Lemail).val();\r\n");
      out.write("\t      $(frm.email).val(email);\r\n");
      out.write("\t   }\r\n");
      out.write("\t   \r\n");
      out.write("      //서밋시\r\n");
      out.write("      $(frm).submit( function(e) {\r\n");
      out.write("         e.preventDefault();\r\n");
      out.write("         \r\n");
      out.write("        makePhone();\r\n");
      out.write("        makeEmail();\r\n");
      out.write("\r\n");
      out.write("        if ($(frm.repwd).val() == \"\") {\r\n");
      out.write("           alert(\"비밀번호를 입력하세요\");\r\n");
      out.write("            $(frm.c_name).focus();\r\n");
      out.write("        } else {\r\n");
      out.write("            if (!confirm(\"회원정보를 수정하시겟습니까?\")) return;\r\n");
      out.write("            frm.submit();\r\n");
      out.write("        }\r\n");
      out.write("   });\r\n");
      out.write("      \r\n");
      out.write("      // 다음 지도\r\n");
      out.write("    function sample6_execDaumPostcode(){\r\n");
      out.write("      new daum.Postcode({\r\n");
      out.write("         oncomplete : function(data) {\r\n");
      out.write("            // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("            // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("            // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("            var addr = ''; // 주소 변수\r\n");
      out.write("            var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("               //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("            if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("               addr = data.roadAddress;\r\n");
      out.write("            }else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("               addr = data.jibunAddress;\r\n");
      out.write("            }\r\n");
      out.write("            // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("            if (data.userSelectedType === 'R') {\r\n");
      out.write("               // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("               // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("               if (data.bname !== '' && /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("                  extraAddr += data.bname;\r\n");
      out.write("               }\r\n");
      out.write("                  // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("               if (data.buildingName !== '' && data.apartment === 'Y') {\r\n");
      out.write("                  extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("               }\r\n");
      out.write("               // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("               if (extraAddr !== '') { extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("               }\r\n");
      out.write("            }\r\n");
      out.write("            // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("            document.getElementById('sample6_postcode').value = data.zonecode;\r\n");
      out.write("            document.getElementById(\"sample6_address\").value = addr;\r\n");
      out.write("            // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("            document.getElementById(\"sample6_detailAddress\") .focus();\r\n");
      out.write("         }\r\n");
      out.write("      }).open();\r\n");
      out.write("   }\r\n");
      out.write("      \r\n");
      out.write("   //재입력 비밀번호 체크하여 가입버튼 비활성화 또는 맞지않음을 알림.\r\n");
      out.write("   function checkPwd() {\r\n");
      out.write("      var inputed = $('#pw').val();\r\n");
      out.write("      var reinputed = $('#repwd').val();\r\n");
      out.write("      // 동일한 비밀번호를 입력했을떄\r\n");
      out.write("      if (inputed == reinputed) {\r\n");
      out.write("         $(\"#btnSave\").prop(\"disabled\", false);\r\n");
      out.write("         $(\"#btnSave\").css(\"background-color\", \"#fff\");\r\n");
      out.write("         $(\"#repwd\").css(\"background-color\", \"#B0F6AC\");\r\n");
      out.write("      // 다른 비밀번호를 입력했을떄   \r\n");
      out.write("      } else if (inputed != reinputed) {\r\n");
      out.write("         $(\"#repwd\").css(\"background-color\", \"#FFCECE\");\r\n");
      out.write("         $(\"#btnSave\").prop(\"disabled\", true);\r\n");
      out.write("         $(\"#btnSave\").css(\"background-color\", \"#aaaaaa\");\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
