/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.5
 * Generated at: 2020-12-11 01:24:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class QnA_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1605611870166L));
    _jspx_dependants.put("jar:file:/D:/Spring%20WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/Spring%20WorkSpace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FP/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/clup.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/search.css\">\r\n");
      out.write("<title>QnA</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "menu.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t<p class=\"clupTitle\">QnA</p>\r\n");
      out.write("\t<div id=\"div_contents\" class=\"contents2\">\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t<div class=\"board_wrap01\">\r\n");
      out.write("\t\t\t<div class=\"board_ty_list\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"notice\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"event\">이벤트</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"QnA\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"board_common01 notice\">\r\n");
      out.write("\t\t\t\t<ul id=\"ulQnAList\"></ul>\r\n");
      out.write("\t\t\t\t<script id=\"temp\" type=\"text/x-handlebars-template\">\r\n");
      out.write("\t\t\t\t{{#each qlist}}\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"type\">공지</div> \r\n");
      out.write("\t\t\t\t\t\t<dl>\r\n");
      out.write("\t\t\t\t\t\t\t<dt>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"QnA_read?q_no={{q_no}}\">{{q_title}}</a>\r\n");
      out.write("\t\t\t\t\t\t\t</dt>\r\n");
      out.write("\t\t\t\t\t\t\t<dd>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"http://s.nx.com/s2/game/mabinogi/mabiweb/homepage/images/common/icon_gm.png\"> 관리자\r\n");
      out.write("\t\t\t\t\t\t\t</dd>\r\n");
      out.write("\t\t\t\t\t\t</dl>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"info_r\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"date\">{{q_regdate}}</span>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t{{/each}}\r\n");
      out.write("\t\t\t\t</script>  \t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"page_wrap\">\r\n");
      out.write("\t\t<div class=\"page_nation\" id=\"page_nation\"></div>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"wrap\">\r\n");
      out.write("\t\t<div class=\"search\">\r\n");
      out.write("\t\t\t<select class=\"select2\">\r\n");
      out.write("\t\t\t\t<option value=\"q_title\">제목</option>\r\n");
      out.write("\t\t\t</select> \r\n");
      out.write("\t\t\t<input type=\"text\" class=\"searchTerm\" id=\"query\" value=\"\">\r\n");
      out.write("\t\t\t<button class=\"searchButton\" id=\"btnSearch\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-search\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar page =1; \r\n");
      out.write("\tgetQnAlist();\r\n");
      out.write("\tfunction getQnAlist(){\r\n");
      out.write("\t\tvar query = $(\"#query\").val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t    \ttype:\"get\",\r\n");
      out.write("\t        url:\"QnAList\",\r\n");
      out.write("\t        data:{\"page\":page,\"query\":query},\r\n");
      out.write("\t        dataType:\"json\",\r\n");
      out.write("\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t       \tvar temp=Handlebars.compile($(\"#temp\").html());\r\n");
      out.write("\t           \t$(\"#ulQnAList\").html(temp(data));\r\n");
      out.write("\t           \t \r\n");
      out.write("\t\r\n");
      out.write("\t           \tvar str=\"\";\r\n");
      out.write("\t           \tvar endPage=0;\r\n");
      out.write("\t           \tif(data.pm.prev){\r\n");
      out.write("\t           \t\tstr += \"<a  class='arrow pprev' href='1'></a>\";\r\n");
      out.write("\t                str += \"<a  class='arrow prev' href='\"+ (data.pm.startPage-1) +\"'></a>\"\r\n");
      out.write("\t\t        }       \r\n");
      out.write("\t           \tfor(var i=data.pm.startPage; i<=data.pm.endPage; i++){\r\n");
      out.write("\t                 if(page==i){\r\n");
      out.write("\t                    str += \"<a href='\"+ i +\"' class='active'>\" + i +\"</a>\";\r\n");
      out.write("\t                    endpage=i;\r\n");
      out.write("\t                 }else{\r\n");
      out.write("\t                    str += \"<a href='\"+ i +\"'>\" + i +\"</a>\";\r\n");
      out.write("\t                    endpage=i;\r\n");
      out.write("\t                 }\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t       \t\tif(data.pm.next){\r\n");
      out.write("\t       \t\t\tstr += \"<a  class='arrow pprev' href='\"+endpage+\"'></a>\";\r\n");
      out.write("\t                str += \"<a  class='arrow next' href='\"+(data.pm.endPage+1)+\"'></a>\";\r\n");
      out.write("\t            }\r\n");
      out.write("\t          \t$(\"#page_nation\").html(str);\r\n");
      out.write("\t          \t$(\"#query\").html(data.query);\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t  \t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$(\"#btnSearch\").on(\"click\",function(){\r\n");
      out.write("\t\tgetQnAlist();\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\t$(\"#query\").keydown(function(key){\r\n");
      out.write("    \tif(key.keyCode==13){\r\n");
      out.write("\t\t\tgetQnAlist();\r\n");
      out.write("    \t}\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("    //페이지네이션\r\n");
      out.write("     $(\"#page_nation\").on(\"click\",\"a\",function(e){\r\n");
      out.write("         e.preventDefault();\r\n");
      out.write("         page=$(this).attr(\"href\");\r\n");
      out.write("         \r\n");
      out.write("         getQnAlist();\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/QnA.jsp(18,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id eq 'master'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\t\r\n");
        out.write("\t\t\t<a href=\"createMasterQnA\"><button class=\"btnwh\">글쓰기</button></a>\r\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }
}
